#!/usr/bin/env python3
# main.py
"""
Entry point for the recon-hackathon tool.

Usage:
    python3 main.py "fragment text here"

Behavior:
- Calls Gemini client to reconstruct the fragment
- Calls the search client using the ORIGINAL fragment + reconstructed text + keywords
- Prints results and writes a Markdown report to recon_reports/
"""

import sys
import os
import json
from datetime import datetime, timezone
from pathlib import Path

# Import your local modules
try:
    from gemini_client import reconstruct as gemini_reconstruct
except Exception as e:
    print("Error importing gemini_client:", e)
    gemini_reconstruct = None

try:
    # search signature expected: search(original_fragment, reconstructed_text, keywords, top_n=5)
    from search_client import search as search_client_search
except Exception as e:
    print("Error importing search_client:", e)
    search_client_search = None

# Simple safe wrapper to ensure recon dict shape
def normalize_recon(recon):
    """
    Ensure recon is a dict with keys:
      - reconstructed_text (str)
      - explanations (list)
      - keywords (list)
      - confidence (float)
    If recon is already a string, wrap it.
    """
    if recon is None:
        return {
            "reconstructed_text": "",
            "explanations": [],
            "keywords": [],
            "confidence": 0.0,
        }
    if isinstance(recon, str):
        return {
            "reconstructed_text": recon,
            "explanations": [],
            "keywords": [],
            "confidence": 0.0,
        }
    if isinstance(recon, dict):
        return {
            "reconstructed_text": str(recon.get("reconstructed_text", "") or ""),
            "explanations": list(recon.get("explanations", []) or []),
            "keywords": list(recon.get("keywords", []) or []),
            "confidence": float(recon.get("confidence", 0.0) or 0.0),
        }
    # unknown type — coerce to string
    return {
        "reconstructed_text": str(recon),
        "explanations": [],
        "keywords": [],
        "confidence": 0.0,
    }

def write_report(original_fragment, recon, sources, out_dir="recon_reports"):
    Path(out_dir).mkdir(parents=True, exist_ok=True)
    ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    fname = f"recon_{ts}.md"
    path = Path(out_dir) / fname

    md_lines = []
    md_lines.append(f"# Recon Report — {ts} UTC")
    md_lines.append("")
    md_lines.append("## 1) Original fragment")
    md_lines.append("")
    md_lines.append(f"> {original_fragment}")
    md_lines.append("")
    md_lines.append("## 2) Reconstructed text (LLM)")
    md_lines.append("")
    md_lines.append(f"**Reconstructed:**\n\n{recon['reconstructed_text']}")
    md_lines.append("")
    md_lines.append(f"**Confidence:** {recon.get('confidence',0.0)}")
    md_lines.append("")
    md_lines.append("**Explanations:**")
    md_lines.append("")
    if recon.get("explanations"):
        for ex in recon["explanations"]:
            md_lines.append(f"- {ex}")
    else:
        md_lines.append("- (none)")
    md_lines.append("")
    md_lines.append("**Keywords:**")
    md_lines.append("")
    if recon.get("keywords"):
        md_lines.append(", ".join(recon["keywords"]))
    else:
        md_lines.append("- (none)")
    md_lines.append("")
    md_lines.append("## 3) Top contextual sources")
    md_lines.append("")
    if sources:
        for i, s in enumerate(sources, start=1):
            title = s.get("title") or s.get("url") or "Untitled"
            url = s.get("url") or ""
            snippet = s.get("snippet") or ""
            md_lines.append(f"{i}. [{title}]({url})")
            if snippet:
                md_lines.append(f"   - {snippet}")
            md_lines.append("")
    else:
        md_lines.append("- No sources found.")
        md_lines.append("")
    md_lines.append("---")
    md_lines.append("_Generated by recon-hackathon_")
    md_text = "\n".join(md_lines)

    path.write_text(md_text, encoding="utf-8")
    return path

def main():
    if len(sys.argv) < 2:
        print("Usage: python3 main.py \"<fragment>\"")
        sys.exit(1)

    fragment = sys.argv[1].strip()
    if not fragment:
        print("Empty fragment provided.")
        sys.exit(1)

    # 1) Call Gemini client
    print("1) Calling Gemini client...")
    recon_raw = None
    try:
        if callable(gemini_reconstruct):
            recon_raw = gemini_reconstruct(fragment)
        else:
            print("No gemini_reconstruct available — using fallback mock.")
            recon_raw = {"reconstructed_text": fragment, "explanations": [], "keywords": [], "confidence": 0.0}
    except Exception as e:
        print("Warning: Gemini client threw an exception — using fallback. Error:", e)
        recon_raw = {"reconstructed_text": fragment, "explanations": [], "keywords": [], "confidence": 0.0}

    recon = normalize_recon(recon_raw)
    print("-> Reconstructed text:")
    # Print reconstructed in readable form (if JSON-like, pretty print)
    try:
        # If reconstructed_text looks like JSON, try to pretty-print
        rt = recon["reconstructed_text"]
        # attempt to parse JSON if present
        if rt.strip().startswith("{") and rt.strip().endswith("}"):
            try:
                obj = json.loads(rt)
                print(json.dumps(obj, indent=2, ensure_ascii=False))
            except Exception:
                print(rt)
        else:
            print(rt)
    except Exception:
        print(recon["reconstructed_text"])

    print()

    # 2) Search web for context
    print("2) Searching web for context...")
    sources = []
    try:
        if callable(search_client_search):
            # new search signature expects original fragment first; older versions may expect 3 args
            try:
                # prefer the new signature: search(original_fragment, reconstructed_text, keywords, top_n=5)
                sources = search_client_search(fragment, recon["reconstructed_text"], recon.get("keywords", []), top_n=5)
            except TypeError:
                # fall back to older signature: search(reconstructed_text, keywords, top_n=5)
                sources = search_client_search(recon["reconstructed_text"], recon.get("keywords", []), top_n=5)
        else:
            print("No search client available — skipping web search.")
    except Exception as e:
        print("Warning: search client failed:", e)
        sources = []

    # Print top sources
    print("-> Top sources:")
    if sources:
        for s in sources:
            title = s.get("title") or s.get("url") or ""
            url = s.get("url") or ""
            print(f"- {url} | {title}")
    else:
        print("- (no sources found)")

    print()

    # 3) Render report
    print("3) Rendering report...")
    try:
        report_path = write_report(fragment, recon, sources)
        print(f"Report saved to {report_path}")
    except Exception as e:
        print("Failed to write report:", e)

if __name__ == "__main__":
    main()
